.travis.yml
=> skip travis installation

CONTRIBUTING.md, README.md
=> Updated Readme/Contributing [skip ci]

Datalib/src/main/java/com/cognizant/cognizantits/datalib/component/Project.java, Datalib/src/main/java/com/cognizant/cognizantits/datalib/component/utils/FileUtils.java, IDE/src/main/java/com/cognizant/cognizantits/ide/main/mainui/components/testdesign/tree/ProjectTree.java, IDE/src/main/java/com/cognizant/cognizantits/ide/main/mainui/components/testdesign/tree/ReusableTree.java, IDE/src/main/java/com/cognizant/cognizantits/ide/main/mainui/components/testexecution/tree/TestSetTree.java
* enhanced logs (Ref #8 )
* updated the delete logs for tree on approval :sweat_smile: 
* file level logs on rename/delete :bangbang: 
* updated sysout to logs for refactor :+1: 
* fixed concurrent modification issue in project data stream :mag:
=> Updated Logs

IDE/src/main/java/com/cognizant/cognizantits/ide/main/Main.java, IDE/src/main/java/com/cognizant/cognizantits/ide/main/ui/StartUp.java
splash screen was visible even after loading ui.
=> splash visibility update

Engine/src/main/java/com/cognizant/cognizantits/engine/drivers/findObjectBy/AngularFindBy.java, GridNode/pom.xml, pom.xml
Galen upgraded to 2.3.4 to be inline with Selenium 3.4
ngwebdriver bumped to 1.0
commons-csv upgraded to 1.4
GridNode Build plugin versions upgraded
Changed code to be compatible with latest ngwebdriver
=> Dependency upgrade

Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/impl/html/HtmlTestCaseHandler.java
* removed duplicate counter for `FailedSteps`
* unified style for step counter
=> Fixed duplicate failed steps counting in report

Resources/Installation.md
File name is incorrect in the command
=> Fixed Typo [skip ci]

Engine/src/main/java/com/cognizant/cognizantits/engine/drivers/WebDriverFactory.java
Used Geckodriver's rest api and installed the addon
https://github.com/mozilla/geckodriver/issues/759#issuecomment-308522851
=>  Added a workaround for Firefox Addon on debug mode #7

Resources/GridNode/lib/ReadMe.txt, Resources/lib/clib/Readme.txt, Resources/lib/commands/Readme.txt
Added directories for the respective sections
=> Create dir for dependent libraries

Resources/Configuration/ReportTemplate/html/detailed.html, Resources/Configuration/ReportTemplate/media/css/galenReport.css, Resources/Configuration/ReportTemplate/media/css/report.css, Resources/Configuration/ReportTemplate/media/js/galenReport.js
* Images (screenshots) aligned properly to the size of the screen.
* Button is added for opening images in new tab (window)
* Display property changed from absolute to fixed so that it will be displayed properly even after scrolling the page.
=> Report screenshot fix

Engine/src/main/java/com/cognizant/cognizantits/engine/drivers/SeleniumDriver.java
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug Fix for #49
* **What is the current behavior?** (You can also link to an open issue here / explain!)
Explained in #49 . 
* **What is the new behavior (if this is a feature change)?**
Added a condition to check for existence of Driver. Check for url only if it is not an instance of `MobileDriver`
=> Fix for #49

.github/issue_template.md, .github/pull_request_template.md
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
fixed issue-type check box in issue_template
commented noise/added info. in pull_template
* **What is the current behavior?** (You can also link to an open issue here / explain!)
issue type renders in code
comments/info is visible
* **What is the new behavior (if this is a feature change)?**
issue type will render as  checkbox
comments/info will be hidden
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no
=> Updated issue_template.md 

IDE/src/main/java/com/cognizant/cognizantits/ide/main/mainui/components/testdesign/testcase/TestCaseToolBar.java
Fix for #57
Feature 
As mentioned in #57 
Tooltip will show selected browser and suggest how to change browser
Nope
=> Added Tooltip to update browsers dynamically.

IDE/src/main/java/com/cognizant/cognizantits/ide/main/explorer/settings/SettingsUI.java, IDE/src/main/java/com/cognizant/cognizantits/ide/main/mainui/components/testdesign/testcase/validation/InputRenderer.java
Bug fix
Refer an issue #61 
Test data sheet validation will be carried out on all the environment
=> added Test data sheet validation to all environments

Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/sync/jira/JIRAClient.java, Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/sync/jira/JIRASync.java, Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/sync/jira/ZAPIClient.java, Engine/src/test/java/com/cognizant/cognizantits/engine/reporting/sync/jira/JIRAClientTest.java
Removed additional `/` from endpoints as it is already added.
Bug Fix
An additional / is present in the end points for JIRA #66 
Removed the additional /
No
=> Fixed invalid endpoint creation in JIRA Sync

Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/sync/AbstractHttpClient.java, Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/sync/BasicHttpClient.java, Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/sync/jira/JIRAClient.java, Engine/src/test/java/com/cognizant/cognizantits/engine/reporting/sync/BasicHttpClientTest.java
- added missing post auth, fixes #70
- updated basicclient test
-  added null attachments validation
see #70 
no
=> fix(engine): added missing post auth, fixes #70

IDE/src/main/java/com/cognizant/cognizantits/ide/main/mainui/EngineConfig.java
Bug Fix
WaitTime set to wrong varaibles #68 
WaitTime set to appropriate variables
No
=> Set the wait time to appropriate variables

Engine/src/main/java/com/cognizant/cognizantits/engine/commands/Command.java, Engine/src/main/java/com/cognizant/cognizantits/engine/execution/data/UserDataAccess.java
Bug Fix
As mentioned in #75 
Changed the default value with current SubIteration
No
=> Modified executeTestCase to take current subIteration. Fixes #75

IDE/src/main/java/com/cognizant/cognizantits/ide/main/mainui/components/testdesign/testcase/TestCaseValidator.java, IDE/src/main/java/com/cognizant/cognizantits/ide/main/mainui/components/testdesign/testcase/validation/ConditionRenderer.java
* **What kind of change does this PR introduce?** 
Bug fix #48 
* **What is the current behavior?**
Currently, there is no validation for the condition column in test design panel. Hence, even if condition column is empty or value provided is wrong it doesn't highlight the error.
Program will validate the `condition` field, for a given `action`, it will check if the field is empty, if not, then if it is needed or if it is in the object repository or not. Based on this, if error is there, then `condition` field will be highlighted with red border.
=> UI Validation for Condition Field in TestDesign Panel

Resources/Configuration/ReportTemplate/html/detailed.html, Resources/Configuration/ReportTemplate/html/summary.html, Resources/Configuration/ReportTemplate/media/js/detailed.js, Resources/Configuration/ReportTemplate/media/js/summary.js
Bug fix
#77 
- Unnecessary elements won't be shown while taking print of the execution report page.
- PASS/FAIL status will be shown in respective colors on print, provided print settings are 
ON for taking color print.
=> feat(engine): print media styles for the reports

Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/SummaryReport.java, Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/sync/jira/ZAPIClient.java
fixes #86 
yes (for old version of jira-zephyr)
creating temp. console to avoid error from jira server upon sending a open
stream
=> fix(engine): updated Jira-Zephyr api, fixes #86

Engine/src/main/java/com/cognizant/cognizantits/engine/commands/Command.java, Engine/src/main/java/com/cognizant/cognizantits/engine/commands/CommonMethods.java, Engine/src/main/java/com/cognizant/cognizantits/engine/commands/Dropdown.java, Engine/src/main/java/com/cognizant/cognizantits/engine/commands/RelativeCommand.java, Engine/src/main/java/com/cognizant/cognizantits/engine/commands/WaitFor.java, Engine/src/main/java/com/cognizant/cognizantits/engine/commands/WebButton.java, Engine/src/main/java/com/cognizant/cognizantits/engine/commands/mobile/nativ/Basic.java, Engine/src/main/java/com/cognizant/cognizantits/engine/commands/mobile/nativ/Gesture.java, Engine/src/main/java/com/cognizant/cognizantits/engine/commands/mobile/nativ/KeyActions.java, pom.xml
see #87 
see #87 
updated actions now throw  `ElementException` when element not found thus break the execution on `breakOnError`
yes, if run on  `breakOnError` (testcase will break execution with the affected action.., which is an expected behaviour)
=> fix(engine) : fixed `ElementException` breakOnError issue  fixes #87

Datalib/pom.xml, Dist/pom.xml, Engine/pom.xml, ExtensionConnect/pom.xml, GridNode/pom.xml, IDE/pom.xml, QcConnection/pom.xml, StoryWriter/pom.xml, TestData - Csv/pom.xml, pom.xml
version upgrade from 1.0 -> 1.1
version upgrade
no
=>  version upgrade from 1.0 -> 1.1

Engine/src/main/java/com/cognizant/cognizantits/engine/reporting/impl/html/bdd/CucumberReport.java
recursive lift any reusable > level1 in a bdd testcase report
bug fix
#95 
any reusable level >1 inside a bdd test case will be lifted as multiple steps
no
1. impacts cucumber bdd reports
2. updated step duration calculation
=> fix(engine): recursive lift any reusable > level1 in a bdd testcase report, fixes #95

IDE/src/main/java/com/cognizant/cognizantits/ide/main/bdd/BddParser.java
=> Fix bdd duplicate def

README.md
Added google docs survey
- [*] The commit message follows our guidelines
- [*] Docs have been added / updated  
Docs update
There was no customer survey
In Readme.md file added google docs survey to know about customer who are download and using the tool
NA
NA
=> Added Google Survey

Resources/Installation.md
Document updates
Demo Project details was not present 
Mac driver configuration and Demo Project details are captured in the new document
No
=> Updating demo project details , mac driver config

README.md
Docs Update
It was displaying unknown  in release badge
It will start showing the current latest release
No
=> Updated Latest Release

Resources/Installation.md
=> Format changes made

.travis.yml
The Maven traces are suppressed while project build
The Travis lines exceeds and fails
Added "mvn -q clean install" -q stands for quiet install
No
=> Update .travis.yml for maven quiet install
